apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZWEp6Wlc0dFluZHVPbWRvY0Y5SFRtb3pWalZXYkhkblJXNTVaRXB0VDJScWNtWjNkV2wwTVdZeFQxZzBVMkU1WlhVPSJ9fX0=
type: kubernetes.io/dockerconfigjson
